/**
 * In-memory FIFO background queue for auto-generating illustrations.
 *
 * One image is generated at a time (no parallelism — respects API rate
 * limits). Settings are re-read before each item so runtime changes take
 * effect without restart.
 *
 * The queue is ephemeral — items do not survive a page reload. Missing
 * images can be regenerated by locking the fact again or re-saving the
 * inventory item.
 */

import { invoke } from "@tauri-apps/api/core";
import { getSetting } from "../db/repositories/settingsRepo";
import {
  getConnection,
  listConnections,
} from "../db/repositories/connectionsRepo";
import { setFactImage } from "../db/repositories/ledgerRepo";
import { setInventoryItemImage } from "../db/repositories/personasRepo";
import { toConnectionDto } from "../providers/dto";
import type { ConnectionConfig } from "../providers/types";

// ---- queue ----------------------------------------------------------------

interface QueueItem {
  type: "fact" | "inventory";
  /** fact.id or persona.id */
  targetId: string;
  prompt: string;
  /** Only for inventory items — which item within the persona's inventory. */
  itemName?: string;
}

const queue: QueueItem[] = [];
let processing = false;
let timerId: ReturnType<typeof setTimeout> | null = null;

// ---- daily rate limiting --------------------------------------------------

let dailyCount = 0;
let lastDate = "";

function getToday(): string {
  return new Date().toISOString().slice(0, 10);
}

function resetDailyIfNeeded(): void {
  const today = getToday();
  if (today !== lastDate) {
    dailyCount = 0;
    lastDate = today;
  }
}

// ---- connection resolution ------------------------------------------------

async function resolveConnection(): Promise<ConnectionConfig | null> {
  const connId = await getSetting("image_gen_connection_id");
  if (connId) {
    return getConnection(connId);
  }
  // Fall back to the first connection that lists "image" in its purposes.
  const all = await listConnections();
  return all.find((c) => c.purposes.includes("image")) ?? null;
}

// ---- main loop ------------------------------------------------------------

async function processQueue(): Promise<void> {
  if (processing) return;
  processing = true;

  try {
    while (queue.length > 0) {
      resetDailyIfNeeded();

      // --- enabled? ---
      // Unset (never saved in Settings → Memory) defaults to enabled, to
      // match the checkbox's own default (useState(true) in
      // MemorySettingsPanel) — only an explicit "0" opts out.
      const enabled = await getSetting("image_gen_enabled");
      if (enabled === "0") {
        queue.length = 0; // disabled → drain the queue silently
        break;
      }

      // --- daily limit ---
      const limitRaw = await getSetting("image_gen_limit");
      const limit = limitRaw ? parseInt(limitRaw, 10) : 0;
      if (limit > 0 && dailyCount >= limit) {
        // Stop processing but leave items in the queue — they'll be
        // picked up tomorrow when the date changes and enqueueIllustration
        // is called again.
        break;
      }

      // --- connection ---
      const connection = await resolveConnection();
      if (!connection) {
        console.warn("imageGenQueue: no connection available for image generation");
        queue.length = 0;
        break;
      }

      const item = queue.shift()!;

      try {
        const imagePath: string = await invoke("generate_illustration", {
          connection: toConnectionDto(connection),
          prompt: item.prompt,
        });

        dailyCount++;

        // Persist the result.
        if (item.type === "fact") {
          await setFactImage(item.targetId, imagePath);
        } else if (item.itemName) {
          await setInventoryItemImage(item.targetId, item.itemName, imagePath);
        }
      } catch (err) {
        console.warn("imageGenQueue: generation failed for", item.type, item.targetId, err);
        // Continue to the next item — don't let one failure stall the queue.
      }
    }
  } finally {
    processing = false;
  }
}

function scheduleProcess(): void {
  // Small delay so items enqueued in the same tick are batched into one
  // processing session, and the caller never blocks on the queue.
  if (timerId !== null) return;
  timerId = setTimeout(() => {
    timerId = null;
    void processQueue();
  }, 300);
}

// ---- public API -----------------------------------------------------------

/**
 * Enqueue an illustration request.
 *
 * @param type      `"fact"` for a ledger fact, `"inventory"` for a persona inventory item.
 * @param targetId  `fact.id` or `persona.id`.
 * @param prompt    The image-generation prompt.
 * @param itemName  Required for `"inventory"` — the `item` field of the inventory entry.
 */
export function enqueueIllustration(
  type: "fact" | "inventory",
  targetId: string,
  prompt: string,
  itemName?: string,
): void {
  // Don't queue duplicates (same type + target + item).
  if (
    queue.some(
      (i) =>
        i.type === type &&
        i.targetId === targetId &&
        (type !== "inventory" || i.itemName === itemName),
    )
  ) {
    return;
  }

  queue.push({ type, targetId, prompt, itemName });
  scheduleProcess();
}
